[package]
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
edition = "2021"
name = "async-local"
version = "0.4.1"
description = "For safely utilizing pointers to thread locals variables within an async context and across await points"
readme = "./README.md"
license = "MIT"
repository = "https://github.com/Bajix/async-local/"

[dependencies]
async_t = "0.7.0"
derive-async-local = { version = "0.4.1", path = "./derive-async-local" }


[dev-dependencies]
doomsday-clock = { path = "./doomsday-clock" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "rt"] }

[target.'cfg(loom)'.dependencies]
loom = { version = "0.5.6", features = [] }

[lib]
doctest = false
bench = false

[features]
default = []
boxed = ["async_t/boxed"]

[workspace]
members = ["derive-async-local", "doomsday-clock"]

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
