[package]
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
edition = "2021"
name = "async-local"
version = "0.6.0"
description = "For safely extending the lifetime of thread locals"
readme = "./README.md"
license = "MIT"
repository = "https://github.com/Bajix/async-local/"

[dependencies]
async_t = "0.7"
async-std = { version = "1", features = ["attributes"], optional = true }
derive-async-local = { version = "0.6.0", path = "./derive-async-local" }
shutdown-barrier = { version = "1", path = "./shutdown-barrier" }
static_assertions = "1.1"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"], optional = true }

[target.'cfg(loom)'.dependencies]
loom = { version = "0.5", features = [] }

[lib]
doctest = false
bench = false

[features]
default = ["tokio-runtime"]
boxed = ["async_t/boxed"]
tokio-runtime = ["tokio"]
async-std-runtime = ["async-std"]

[workspace]
members = ["derive-async-local", "doomsday-clock", "shutdown-barrier"]

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1

[package.metadata.docs.rs]
features = ["boxed", "tokio-runtime", "async-std-runtime"]
all-features = false
rustdoc-args = ["--cfg", "docsrs"]
