[package]
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
edition = "2021"
name = "async-local"
version = "0.5.1"
description = "For safely utilizing pointers to thread locals variables within an async context and across await points"
readme = "./README.md"
license = "MIT"
repository = "https://github.com/Bajix/async-local/"

[dependencies]
async_t = "0.7.0"
async-std = { version = "1", features = [], optional = true }
derive-async-local = { version = "0.5.0", path = "./derive-async-local" }
shutdown-barrier = { version = "0.1.0", path = "./shutdown-barrier" }
static_assertions = "1.1.0"
tokio = { version = "1", features = ["rt"], optional = true }

[dev-dependencies]
doomsday-clock = { path = "./doomsday-clock" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "rt"] }

[target.'cfg(loom)'.dependencies]
loom = { version = "0.5.6", features = [] }

[lib]
doctest = false
bench = false

[features]
default = ["tokio-runtime"]
boxed = ["async_t/boxed"]
tokio-runtime = ["tokio"]
async-std-runtime = ["async-std"]

[workspace]
members = ["derive-async-local", "doomsday-clock", "shutdown-barrier"]

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
