[package]
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
edition = "2021"
name = "async-local"
version = "0.12.0"
description = "For safely extending the lifetime of thread locals"
readme = "./README.md"
license = "MIT"
repository = "https://github.com/Bajix/async-local/"

[dependencies]
derive-async-local = { version = "0.12.0", path = "./derive-async-local" }
num_cpus = "1"
pin-project = "1"
tokio = { version = "1", features = [
  "macros",
  "rt",
] }

[dev-dependencies]
async-trait = "0.1.64"

[target.'cfg(loom)'.dependencies]
loom = { version = "0.5", features = [] }

[lib]
doctest = false
bench = false

[features]
default = ["rt-multi-thread"]
rt-multi-thread = ["tokio/rt-multi-thread"]

[workspace]
members = [
  "derive-async-local"
]

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1

[package.metadata.docs.rs]
features = []
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
