[package]
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
edition = "2021"
name = "async-local"
version = "0.15.3"
description = "For safely extending the lifetime of thread locals"
readme = "./README.md"
license = "MIT"
repository = "https://github.com/Bajix/async-local/"

[dependencies]
derive-async-local = { version = "0.15.0", path = "./derive-async-local" }
num_cpus = "1"
pin-project = "1"
static_assertions = "1.1"
tokio = { version = "1", features = ["rt", "rt-multi-thread"], optional = true }

[dev-dependencies]
async-trait = "0.1.64"
tokio = { version = "1", features = ["macros"] }

[target.'cfg(loom)'.dependencies]
loom = { version = "0.5", features = [] }

[lib]
doctest = false
bench = false

[features]
default = ["tokio-runtime", "leaky-context"]

# Enable with_blocking to spawn blocking tasks onto the Tokio Runtime
tokio-runtime = ["tokio"]

# Compatibilty flag that makes Context<T> substitute Box::leak instead of relying the internal barrier-protected Runtime to ensure tasks never outlive runtime worker owned thread local data by rendezvousing during shutdown
leaky-context = []

# Tokio Runtime configured with a barrier-synchronized shutdown as to ensure tasks never outlive worker thread owned local data
barrier-protected-runtime = ["tokio-runtime", "tokio/rt-multi-thread"]

[workspace]
members = ["derive-async-local"]

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1

[package.metadata.docs.rs]
all-features = false
rustdoc-args = ["--cfg", "docsrs"]
