version: "3"

env:
  TARGET: x86_64-apple-darwin

tasks:
  default:
    cmds:
      - task: clippy-tests
      - task: test-address-sanitizer

  test-miri:
    cmds:
      - cargo miri test -Z build-std --target $TARGET -- --nocapture
    env:
      MIRIFLAGS: -Zmiri-backtrace=full -Zmiri-disable-isolation

  doc:
    cmds:
      - cargo +nightly doc -p async-local --open
    env:
      RUSTDOCFLAGS: --cfg docsrs

  clippy-tests:
    cmds:
      - cargo clippy --tests

  check-tests:
    cmds:
      - cargo check --tests

  check-loom:
    cmds:
      - cargo check --tests
    env:
      RUSTFLAGS: --cfg loom

  test-loom:
    cmds:
      - cargo test -p async-local -- --nocapture
    env:
      RUSTFLAGS: --cfg loom

  test-address-sanitizer:
    cmds:
      - cargo test -Z build-std --target $TARGET -- --nocapture
    ev:
      RUSTFLAGS: -Z sanitizer=address
