version: "3"

env:
  TARGET: x86_64-apple-darwin

tasks:
  default:
    cmds:
      - task: test
      - task: clippy-tests
      - task: test-address-sanitizer

  test:
    cmds:
      - cargo test --features barrier-protected-runtime -- --nocapture

  test-miri:
    cmds:
      - cargo miri test -Z build-std --target $TARGET --features barrier-protected-runtime -- --nocapture
    env:
      MIRIFLAGS: -Zmiri-backtrace=full -Zmiri-disable-isolation

  doc:
    cmds:
      - cargo +nightly doc -p async-local --open --features barrier-protected-runtime
    env:
      RUSTDOCFLAGS: --cfg docsrs

  clippy-tests:
    cmds:
      - cargo clippy --tests --features barrier-protected-runtime

  check-tests:
    cmds:
      - cargo check --tests --features barrier-protected-runtime

  test-address-sanitizer:
    cmds:
      - cargo test -Z build-std --target $TARGET --features barrier-protected-runtime -- --nocapture
    ev:
      RUSTFLAGS: -Z sanitizer=address
